<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\CleanTemplate.Domain\CleanTemplate.Domain.csproj" />
    <ProjectReference Include="..\CleanTemplate.SharedKernel\CleanTemplate.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mediora" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

</Project>
